### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by gee-contrib** [gee-community/GEE-Dev-Docs#2]
does Just-the-Docs allow syntax highlighting? I found this on jekyll, so maybe this can work for this repo?
https://mycyberuniverse.com/en-gb/syntax-highlighting-jekyll.html

**Comment by jdbcode** [comment]
Yes, it is using Jekyll’s built-in syntax highlighting with Rouge, which is what is suggested in the page you linked to. I added a demo of it to this page: 

https://gee-community.github.io/GEE-Dev-Docs/docs/methods/specific/methods-specific-topic2.html.

It looks like we could probably use a different method or theme if we thought there is something better.
