### ISSUE TITLE
Footer link to source

### ISSUE THREAD

**Issue by gee-contrib** [gee-community/GEE-Dev-Docs#4]
It would be useful to have a footer that automatically link to the source file, so people can in a single click get to the correct file and edit it (creating a forked version and submitting pull request).  I think the file structure is maintained, so it is basically changing the .html with .md and shifting the base directory.... Not something I know how to do, however :-(

**Comment by gee-contrib** [comment]
Perhaps something like this example can work here? 
https://github.com/jekyll/jekyll-help/issues/5

**Comment by gee-contrib** [comment]
Perhaps something like this example can work here? 
https://github.com/jekyll/jekyll-help/issues/5

**Comment by jdbcode** [comment]
This is a great idea - yes! One of the examples in the link you sent worked. Here is a demo - see the end of example 1:  https://gee-community.github.io/GEE-Dev-Docs/docs/methods/specific/methods-specific-topic2.html

This is the line: <a href="{{ site.github.repository_url }}/tree/master/{{ page.path }}">Edit this</a>

We could make it look better, but at least there is a solution.

**Comment by gee-contrib** [comment]
It would be better to make the link text much more descriptive e.g.  

To edit this page (i) click here; (ii) select "edit the file in your fork of the project" (pencil icon); (iii) write your suggestion using Markdown; (iv) add a short description of your edits and (v) select "propose file change" to submit the change to review

**Comment by gee-contrib** [comment]
It would also be good if this is automatically part of the layout, and not something we need to put in in each page. I wonder - if you create a _layout directory in the Repo root and make a modified copy of https://github.com/pmarsceill/just-the-docs/blob/master/_layouts/default.html will that work ?

**Comment by guy1ziv2** [comment]
yes, it does work. I made such a default.html and an edit link like I proposed above shows well on each page
